package com.bytevault.gateway;
import javax.crypto.spec.SecretKeySpec; import javax.crypto.SecretKey; import org.springframework.beans.factory.annotation.Value; import org.springframework.cloud.gateway.route.RouteLocator; import org.springframework.cloud.gateway.route.builder.RouteLocatorBuilder; import org.springframework.context.annotation.*; import org.springframework.security.config.web.server.ServerHttpSecurity; import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity; import org.springframework.security.oauth2.jose.jws.MacAlgorithm; import org.springframework.security.oauth2.jwt.NimbusReactiveJwtDecoder; import org.springframework.security.oauth2.jwt.ReactiveJwtDecoder; import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationConverter; import org.springframework.security.oauth2.server.resource.authentication.JwtGrantedAuthoritiesConverter; import org.springframework.security.oauth2.server.resource.authentication.ReactiveJwtAuthenticationConverterAdapter; import org.springframework.security.web.server.SecurityWebFilterChain;
@Configuration @EnableMethodSecurity public class GatewayConfig{
 @Bean SecretKey jwtSecret(@Value("${security.jwt.secret}")String secret){return new SecretKeySpec(secret.getBytes(java.nio.charset.StandardCharsets.UTF_8),"HmacSHA256");}
 @Bean ReactiveJwtDecoder jwtDecoder(SecretKey key){return NimbusReactiveJwtDecoder.withSecretKey(key).macAlgorithm(MacAlgorithm.HS256).build();}
 @Bean SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http,ReactiveJwtDecoder decoder){
  JwtGrantedAuthoritiesConverter authorities=new JwtGrantedAuthoritiesConverter(); authorities.setAuthoritiesClaimName("roles"); authorities.setAuthorityPrefix("ROLE_"); JwtAuthenticationConverter c=new JwtAuthenticationConverter();c.setJwtGrantedAuthoritiesConverter(authorities);
  return http.csrf(csrf->csrf.disable()).authorizeExchange(ex->ex.pathMatchers("/","/index.html","/css/**","/js/**","/api/auth/**","/api/products","/api/products/**","/api/orders/download/**","/actuator/health/**").permitAll().anyExchange().authenticated()).oauth2ResourceServer(o->o.jwt(j->j.jwtDecoder(decoder).jwtAuthenticationConverter(new ReactiveJwtAuthenticationConverterAdapter(c)))).build();
 }
 @Bean RouteLocator routes(RouteLocatorBuilder b){return b.routes().route("user-service",r->r.path("/api/auth/**","/api/users/**").uri("lb://USER-SERVICE")).route("product-service",r->r.path("/api/products/**").uri("lb://PRODUCT-SERVICE")).route("order-service",r->r.path("/api/orders/**").uri("lb://ORDER-SERVICE")).build();}
}
